config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  root to: 'homepage#index'
  get "/posts/export", to: "posts#export", as: :export

  resources :posts
  get "posts/:id/tags",to: "posts#tags", as: :tag_post 
  post "posts/:id/tags",to: "tags#add"
  post "posts/:id/tagsremove",to: "tags#remove", as: :remove_tag
  get "/tags/:id",to: "tags#show", as: :show_tag

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    has_and_belongs_to_many :tags
    has_rich_text :body
    validates :title, presence: true, uniqueness: {case_sensitive: false}

    def add_tag(tag)
        if !self.tags.include?(tag)
            self.tags << tag
        end
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :posts
    validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    email == "n.katrin.kim@gmail.com"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def need_admin_role
    unless user_signed_in? && current_user.admin?
      redirect_to new_user_session_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :need_admin_role, only: :destroy

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:commenter, :body, :post_id)
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :tags]
  before_action :need_admin_role, only: :destroy

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(title: :asc)
  end

  def export
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  def tags
    @post = Post.find params[:id]
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to tag_post_path(@post), notice: 'Post wurde erfolgreich erstellt' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, alert: 'Titel darf nicht leer sein oder schon existierten Namen haben'}
        # format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post wurde erfolgreich editiert' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post wurde gelöscht' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!, only: [:add, :edit, :update]
  before_action :need_admin_role, only: :destroy

  def add
    @post = Post.find params[:id]
    tag = Tag.find_or_create_by(name: params[:tag])
    
    if tag.valid?
      @post.add_tag(tag)
      redirect_to tag_post_path(@post)
    else
      redirect_to tag_post_path(@post), alert: "Tag darf nicht leer sein oder gleichen Namen haben"
    end
  end

  def remove
    post = Post.find params[:id]
    tag = Tag.find params[:tag_id]
    if post.tags.delete(tag)
      redirect_to tag_post_path(post), notice: "Tag wurde gelöscht"
    end
    
  end

  def show
    @tag = Tag.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.haml
%figure{:class => "attachment attachment--#{blob.representable? ? "preview" : "file"} attachment--#{blob.filename.extension}"}
  - if blob.representable?
    = image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])
  %figcaption.attachment__caption
    - if caption = blob.try(:caption)
      = caption
    - else
      %span.attachment__name= blob.filename
      %span.attachment__size= number_to_human_size blob.byte_size

app/views/comments/_form.html.haml
%body
  = form_with(model: comment, local: true) do |form|
    - if comment.errors.any?
      #error_explanation
        -# %h2
        -#   = pluralize(comment.errors.count, "error")
        -#   prohibited this comment from being saved:
        %ul
          - comment.errors.full_messages.each do |message|
            %li= message

    .form-group.white-on-black
      = form.label :commenter, 'Autor'
      = form.text_field :commenter, class: 'form-control', placeholder: 'Name'
    .form-group.white-on-black
      = form.label :body, 'Kommentar'
      = form.text_area :body, class: 'form-control', rows: 3, placeholder: 'Vorschläge, Bemerkungen'
    .form-group.white-on-black
      = form.label :post_id, 'Post id'
      = form.text_field :post_id, class: 'form-control'
    %button.btn.btn-primary{:type => "submit"} Abschicken

app/views/comments/edit.html.haml
%body
  %p Kommentar editieren
  = render 'form', comment: @comment
  = link_to 'Show', @comment
  |
  \#{link_to 'Back', comments_path}

app/views/comments/index.html.haml
%p Eure Bewertungen und Bemerkungen machen die Rezepte noch besser!

.white-on-black
  %table.table.table-hover.table-responsive
    %thead
      %tr
        %th.w30 Autor
        %th.w55 Kommentar
        %th Post
        %th{:colspan => "3"} Funktion
    %tbody
      - @comments.each do |comment|
        %tr
          %td= comment.commenter
          %td= comment.body
          %td= comment.post_id
          %td= link_to 'Show', comment
          %td= link_to 'Edit', edit_comment_path(comment)
          %td= link_to 'Löschen', comment, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%body
  %p Kommentar schreiben
  = render 'form', comment: @comment
  = link_to 'Back', comments_path

app/views/comments/show.html.haml
%p
  %strong Autor:
  = @comment.commenter
%p
  %strong Kommentar:
  = @comment.body
%p
  %strong Post:
  = @comment.post_id
= link_to 'Edit', edit_comment_path(@comment)
|
\#{link_to 'Back', comments_path}

app/views/homepage/index.html.haml
.tags-oben
  - Tag.all.each do |tag|
    %a.mbadge.badge-primary{:href => show_tag_path(tag)}
      %h6.titel-font= tag.name
%br/
.mcontainer.mobile
  .row.space-bw
    - @posts.each do |post|
      .allert.alert-prim.flex{:role => "allert"}
        %h3= link_to post.title, post
        %p.font== #{time_ago_in_words post.created_at} ago
        .tags  
          - post.tags.each do |tag|
            %a.badge.badge-primary{:href => show_tag_path(tag)}= tag.name

app/views/layouts/_footer.html.haml
%footer
  .btn-position
    %a{:href => "#"}
      %button.mbtn{:type => "button"}
        %i.material-icons arrow_upward

app/views/layouts/_header.html.haml
%header
  .header
    .titel 
      %a{:href => "/"} Rezeptenbibliothek

    %nav.nav.nav-pills.justify-content-end.top-menu
      - if user_signed_in?
        - if current_user.admin?
          %li.nav-item
            %a.nav-link{:href => "/posts"} Posts
        
        %li.nav-item
          %a.nav-link.active{:href => "/posts/new"} New Post
        
        - if current_user.admin?
          %li.nav-item
            %a.nav-link{:href => "/comments"} Comments

        %li.nav-item
          = link_to "Logout", destroy_user_session_path, class: "nav-link", method: :delete 
      
      - else
        %li.nav-item
          = link_to "Login", new_user_session_path, class: "nav-link"
          -# %a.nav-link.active{:href => "/users/sign_in"} Login

  - if flash[:notice].present?
    .alert.alert-info.success{role: "alert"}
      = sanitize flash[:notice], tags: %w(br ul li strong)
      -# %button.close{"data-dismiss": "alert", type: "button"} ×

  -# - if flash[:alert].present?
  -#   .alert.alert-danger{role: "alert"}
  -#     = sanitize flash[:alert], tags: %w(br ul li strong)
      -# %button.close{"data-dismiss": "alert", type: "button"} ×

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blog
    = csrf_meta_tags
    = csp_meta_tag
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{:crossorigin => "anonymous", :href => "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css", :integrity => "sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z", :rel => "stylesheet"}/
    %link{:href => "https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons", :rel => "stylesheet"}/

    %link{:href => "https://fonts.googleapis.com", :rel => "preconnect"}/
    %link{:crossorigin => "", :href => "https://fonts.gstatic.com", :rel => "preconnect"}/
    %link{:href => "https://fonts.googleapis.com/css2?family=Indie+Flower&family=Lobster+Two&display=swap", :rel => "stylesheet"}/

    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"}
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    %script{:crossorigin => "anonymous", :integrity => "sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj", :src => "https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"}

  %body
    %main.container
      = render "layouts/header"
      %article
        = yield
    = render "layouts/footer"
  

app/views/posts/_form.html.haml
= form_with(model: post, local: true) do |form|
  - if post.errors.any?
    .alert.danger
      Titel darf nicht leer sein oder schon existierten Namen haben

  .form-group.white-on-black
    = form.label :title, 'Titel'
    = form.text_field :title, class: 'form-control'
  .field.white-on-black
    = form.label :body, 'Rezept'
    = form.rich_text_area :body, placeholder: 'Zutaten, Schritte'  
  %br
  
  %button.btn.btn-primary{:type => "submit"} Abschicken

app/views/posts/edit.html.haml
%body
  %p Post editieren
  = render 'form', post: @post
  = link_to 'Show', @post
  |
  \#{link_to 'Back', posts_path}

app/views/posts/export.html.haml
- data = {}
- data[:posts] = Post.all
= data.to_json

app/views/posts/index.html.haml
%p Alles, was wir hier bisher gesammelt haben:

.white-on-black
  %table.table.table-hover.table-responsive
    %thead
      %tr
        %th.w55 Titel
        %th.w30 Tags
        %th{:colspan => "3"} Funktion
    %tbody
      - @posts.each do |post|
        %tr
          %td.font= link_to post.title, post
          %td
            - post.tags.each do |tag|
              %a.badge.badge-primary{:href => "#{show_tag_path(tag)}"}
                = tag.name
          %td= link_to 'Edit', edit_post_path(post)
          %td= link_to '+Tags', tag_post_path(post)
          %td= link_to 'x', post, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%body
  %p Ein neues leckeres Rezept gefunden? Speicher es schneller hier!
  = render 'form', post: @post
  %br/
  = link_to 'Back', posts_path

app/views/posts/show.html.haml
.post-headline.font.white
  %h4= @post.title
%p.titel-font
  %strong Zutaten:
  = @post.body
%div
  - @post.tags.each do |tag|
    %a.badge.badge-primary{:href => "#{show_tag_path(tag)}"}= tag.name
%br/
%h5.titel-font.white Kommentare:
.panel.panel-primary
  %ul
    - @post.comments.each do |comment|
      %li.white
        "#{comment.body}" von #{comment.commenter}

.collabsible
  %button.btn.btn-primary.titel-font#add_comment Kommentar hinzufügen
  .form
    = form_for @comment do |f|
      .form-group.white-on-black
        = f.label :commenter, 'Autor'
        = f.text_field :commenter, class: 'form-control', placeholder: 'Name'
      .form-group.white-on-black
        = f.label :body, 'Kommentar'
        = f.text_area :body, class: 'form-control', rows: 3, placeholder: 'Vorschläge, Bemerkungen'
      = f.hidden_field :post_id, value: @post.id
      %button.btn.btn-primary{:type => "submit"} Abschicken
%br

= link_to 'Edit', edit_post_path(@post)
|
\#{link_to 'Back', posts_path}

app/views/posts/tags.html.haml
%p.heading Tags hinzufügen
%h4.white.font
  = @post.title

= form_with(remote: false, local: true, url:tag_post_path(@post)) do |f|
  - if alert.present?
    .alert.danger
      Tag darf nicht leer sein oder schon existierten Namen haben

  .form-group.white-on-black
    = f.label :tag
    = f.text_field :tag, class: 'form-control'
  = f.hidden_field :post_id, value: @post.id
  %button.btn.btn-primary{:type => "submit"} Abschicken

%p
  - @post.tags.each do |tag|
    %div
      = form_with(url:remove_tag_path(@post)) do |form|
        = form.hidden_field :tag_id, value: tag.id
        = form.submit "x"
        %a.badge.badge-primary= tag.name

app/views/tags/show.html.haml
.mbadge.badge-primary.m-bottom
  %h6.titel-font= @tag.name

.mcontainer.negative-marg
  .space-bw
    - @tag.posts.each do |post|
      .allert.alert-prim.flex{:role => "allert"}
        %h3= link_to post.title, post
        %p== #{time_ago_in_words post.created_at} ago
        .tags
          - post.tags.each do |tag|
            %a.badge.badge-primary{:href => "#{show_tag_path(tag)}"}= tag.name